package com.my.scaffold.dal.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zcy_sku_create_record
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ZcySkuCreateRecord {
    /**
     *   
     * zcy_sku_create_record.id
     */
    private Long id;

    /**
     *   土猫sku编码
     * zcy_sku_create_record.sku_code
     */
    private String skuCode;

    /**
     *   所在政采云sku id
     * zcy_sku_create_record.sku_id
     */
    private Long skuId;

    /**
     *   土猫spu编码(实际是sku编码代替，保证唯一性即可)
     * zcy_sku_create_record.item_code
     */
    private String itemCode;

    /**
     *   所在政采云spu id
     * zcy_sku_create_record.item_id
     */
    private Long itemId;

    /**
     *   
     * zcy_sku_create_record.gmt_create
     */
    private Date gmtCreate;

    /**
     *   
     * zcy_sku_create_record.gmt_modify
     */
    private Date gmtModify;

    /**
     *   
     * zcy_sku_create_record.enabled
     */
    private boolean enabled;

    /**
     *   是否已申请上架
     * zcy_sku_create_record.apply_shelf
     */
    private Integer applyShelf;

    /**
     * 获取  字段：zcy_sku_create_record.id
     *
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置  字段：zcy_sku_create_record.id
     *
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 土猫sku编码 字段：zcy_sku_create_record.sku_code
     *
     */
    public String getSkuCode() {
        return skuCode;
    }

    /**
     * 设置 土猫sku编码 字段：zcy_sku_create_record.sku_code
     *
     */
    public void setSkuCode(String skuCode) {
        this.skuCode = skuCode == null ? null : skuCode.trim();
    }

    /**
     * 获取 所在政采云sku id 字段：zcy_sku_create_record.sku_id
     *
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * 设置 所在政采云sku id 字段：zcy_sku_create_record.sku_id
     *
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * 获取 土猫spu编码(实际是sku编码代替，保证唯一性即可) 字段：zcy_sku_create_record.item_code
     *
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * 设置 土猫spu编码(实际是sku编码代替，保证唯一性即可) 字段：zcy_sku_create_record.item_code
     *
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * 获取 所在政采云spu id 字段：zcy_sku_create_record.item_id
     *
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * 设置 所在政采云spu id 字段：zcy_sku_create_record.item_id
     *
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * 获取  字段：zcy_sku_create_record.gmt_create
     *
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * 设置  字段：zcy_sku_create_record.gmt_create
     *
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * 获取  字段：zcy_sku_create_record.gmt_modify
     *
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * 设置  字段：zcy_sku_create_record.gmt_modify
     *
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * 获取  字段：zcy_sku_create_record.enabled
     *
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * 设置  字段：zcy_sku_create_record.enabled
     *
     */
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * 获取 是否已申请上架 字段：zcy_sku_create_record.apply_shelf
     *
     */
    public Integer getApplyShelf() {
        return applyShelf;
    }

    /**
     * 设置 是否已申请上架 字段：zcy_sku_create_record.apply_shelf
     *
     */
    public void setApplyShelf(Integer applyShelf) {
        this.applyShelf = applyShelf;
    }

    /**
     * 
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", skuCode=").append(skuCode);
        sb.append(", skuId=").append(skuId);
        sb.append(", itemCode=").append(itemCode);
        sb.append(", itemId=").append(itemId);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModify=").append(gmtModify);
        sb.append(", enabled=").append(enabled);
        sb.append(", applyShelf=").append(applyShelf);
        sb.append("]");
        return sb.toString();
    }

    /**
     * 
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ZcySkuCreateRecord other = (ZcySkuCreateRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSkuCode() == null ? other.getSkuCode() == null : this.getSkuCode().equals(other.getSkuCode()))
            && (this.getSkuId() == null ? other.getSkuId() == null : this.getSkuId().equals(other.getSkuId()))
            && (this.getItemCode() == null ? other.getItemCode() == null : this.getItemCode().equals(other.getItemCode()))
            && (this.getItemId() == null ? other.getItemId() == null : this.getItemId().equals(other.getItemId()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModify() == null ? other.getGmtModify() == null : this.getGmtModify().equals(other.getGmtModify()))
            && (this.isEnabled() == other.isEnabled())
            && (this.getApplyShelf() == null ? other.getApplyShelf() == null : this.getApplyShelf().equals(other.getApplyShelf()));
    }

    /**
     * 
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSkuCode() == null) ? 0 : getSkuCode().hashCode());
        result = prime * result + ((getSkuId() == null) ? 0 : getSkuId().hashCode());
        result = prime * result + ((getItemCode() == null) ? 0 : getItemCode().hashCode());
        result = prime * result + ((getItemId() == null) ? 0 : getItemId().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModify() == null) ? 0 : getGmtModify().hashCode());
        result = prime * result + (isEnabled() ? 1231 : 1237);
        result = prime * result + ((getApplyShelf() == null) ? 0 : getApplyShelf().hashCode());
        return result;
    }
}